const List<String> kCountries = [
  'Tunisia',
  'Algeria',
  'Morocco',
  'Libya',
  'Egypt',
  'France',
  'Italy',
  'Spain',
  'Germany',
  'United Kingdom',
  'Turkey',
  'Greece',
  'United States',
  'Canada',
  'Brazil',
  'Mexico',
  'Japan',
  'China',
  'India',
  'Australia',
];

/// Example mapping of popular cities per country.
/// This is a curated offline list for the main countries
/// you are likely to use in the project. You can keep
/// extending it if you want more detail.
const Map<String, List<String>> kCountryCities = {
  'Tunisia': [
    'Tunis',
    'Sfax',
    'Sousse',
    'Bizerte',
    'Gabes',
    'Djerba',
    'Kairouan',
    'Gafsa',
    'Monastir',
    'Nabeul',
    'Tozeur',
    'Mahdia',
    'Ariana',
    'Ben Arous',
  ],
  'Algeria': [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Setif',
    'Batna',
    'Tlemcen',
  ],
  'Morocco': [
    'Casablanca',
    'Rabat',
    'Marrakesh',
    'Fez',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
  ],
  'France': [
    'Paris',
    'Lyon',
    'Marseille',
    'Nice',
    'Toulouse',
    'Bordeaux',
    'Lille',
    'Nantes',
    'Strasbourg',
    'Montpellier',
  ],
  'Italy': [
    'Rome',
    'Milan',
    'Florence',
    'Naples',
    'Venice',
    'Turin',
    'Bologna',
    'Genoa',
  ],
  'Spain': [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Bilbao',
    'Zaragoza',
    'Malaga',
    'Granada',
  ],
  'Germany': [
    'Berlin',
    'Munich',
    'Hamburg',
    'Frankfurt',
    'Cologne',
    'Stuttgart',
    'Düsseldorf',
  ],
  'United Kingdom': [
    'London',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Leeds',
    'Glasgow',
    'Edinburgh',
    'Bristol',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Miami',
    'San Francisco',
    'Las Vegas',
    'Orlando',
    'Boston',
  ],
  'Canada': [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Ottawa',
    'Calgary',
    'Quebec City',
  ],
  'Brazil': [
    'Rio de Janeiro',
    'São Paulo',
    'Brasília',
    'Salvador',
    'Fortaleza',
  ],
  'Mexico': [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Cancún',
    'Puebla',
  ],
  'Japan': [
    'Tokyo',
    'Osaka',
    'Kyoto',
    'Nagoya',
    'Yokohama',
  ],
  'China': [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
  ],
  'India': [
    'New Delhi',
    'Mumbai',
    'Bangalore',
    'Chennai',
    'Hyderabad',
  ],
  'Australia': [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
  ],
};

